version: 1.10.4-{build}
image: Visual Studio 2019
init:
- cmd: >-
    SET JAVA_HOME=C:\Program Files\Java\jdk13

    SET PATH=%JAVA_HOME%\bin;%PATH%

    SET JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
cache: C:\Users\appveyor\.m2
build_script:
- cmd: >-
    echo Source encoding defined with: JAVA_TOOL_OPTIONS=%JAVA_TOOL_OPTIONS%

    java -version

    mvn --version

    mvn clean install -Plinux -DskipTests
artifacts:
- path: target\Filius-Setup*.exe
  name: Windows Installer
- path: target\*.zip
  name: Zip Archive
- path: target\*.deb
  name: Debian Package